name = "parse-email"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[vars]
API_KEY = "123456"
API_URL = "https://forgetmail-api-529748222931.asia-southeast1.run.app"

[observability]
enabled = true